### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock' (Windows)

### ISSUE THREAD

**Issue by Milithor** [xmikos/qspectrumanalyzer#78]
Latest version does not work on Windows with Python 3.8.2.
Error shown: `AttributeError: module 'time' has no attribute 'clock'`

Feedback online says this time function has been deprecated since Python 3.3.
However, your guide says to download a Python version above 3.3.
